### ISSUE TITLE
bug: cancel on component unmount

### ISSUE THREAD

**Issue by bvalosek** [angelle-sw/use-fetch-hooks#7]
This kinna pattern requires that you handle the case wherein a component using this hook is unmounted from the tree before the promise completes. If this happens, you'll get a React error from calling set state on a stale component.

Update your state model and logic to accommodate this

**Comment by zakangelle** [comment]
Dig it. Was also thinking we should consider returning a `cancel` function that can be called imperatively by the consumer.

**Comment by zakangelle** [comment]
Also nice use of "wherein" 10/10

**Comment by jpangelle** [comment]
Great suggestion!

**Comment by jpangelle** [comment]
Thoughts on these two [options](https://stackoverflow.com/questions/49906437/how-to-cancel-a-fetch-on-componentwillunmount#49906662) to cancel when the component unmounts:

**Comment by bvalosek** [comment]
the example of using `useRef` to have a stateful flag that is set on unmount is how I would do it

**Comment by zakangelle** [comment]
To be clear, those examples don't cancel the in-flight request, they just cancel any state updates that are triggered when a request promise resolves/rejects, which prevents React from throwing an error.

Since we're using `axios`, which uses [XHR](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest) under the hood, we can actually cancel in-flight requests using the [axios cancel API](https://github.com/axios/axios#cancellation).

We'll probably want to do both, since there's a chance a component unmounts after the request promise resolves, but _before_ the state update happens.

**Comment by bvalosek** [comment]
> We'll probably want to do both

definitely, I'd consider the "ensure we don't set state after a request completes if the component has unmounted" to be the primary goal, and "cancel an in-flight request" to be a nice-to-have optimization
